---
- name: reboot the system
  command: systemctl reboot
  async: 5
  poll: 0
  sudo: yes
  ignore_errors: true

- name: wait until the system is down
  local_action: wait_for host={{ inventory_hostname }} port=22 state=stopped

- name: wait until the system is up
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started
